version: '2.4'
services:
  db:
    image: postgres
    platform: "linux/amd64"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    platform: "linux/amd64"
    env_file:
      - docker-compose.env
    build: .
    command: tail -f /dev/null
    environment:
      DB_HOST: db
    volumes:
      - .:/planner
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data:
  gem_cache:
